---
- name: Download rpm package
  command: 'wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.rpm"'
  changed_when: false

- name: Install Oracle Java
  yum: pkg=jdk-8u45-linux-x64.rpm state=present

- name: Set Java default
  shell: alternatives --install /usr/bin/java java /usr/java/latest/bin/java 2
