---
- name: Ensure dependencies are installed.
  yum: pkg=curl state=installed

- name: Install python lib.
  yum: name=libselinux-python state=latest

- name: Install wget.
  yum: name=wget state=latest

- name: Install java oracle.
  include: oracle-RedHat.yml

- name: Disable firewall.
  action: service name=iptables state=stopped enabled=false

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"

- name: Ensure Jenkins is installed.
  yum: pkg=jenkins state=installed
